name: "Deploy Web App with Docker Compose"

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'terraform/**'

jobs:
  deploy:
    name: "Deploy Multi-Container App via SSH"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Execute Remote Docker Compose Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.PORT_SSH }}
          script: |
            if [ ! -d "~/terraform-port-server" ]; then
              git clone https://github.com/pyaephyo47/terraform-portfolio.git ~/terraform-port-server
            fi

            cd ~/terraform-port-server
            git checkout main
            git pull origin main

            # Dynamically generate the secure .env file on the live server
            echo "DB_USER=${{ secrets.DB_USER }}" > .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env

            sudo docker compose down || true
            sudo docker compose up -d --build

